[phases.setup]
nixPkgs = ['python311']

[phases.build]
cmds = ['pip install -r adreport/backend/requirements.txt']

[phases.run]
cmds = ['cd adreport/backend && uvicorn main:app --host 0.0.0.0 --port $PORT']
