[build]
builder = "NIXPACKS"
nixpacksProviders = ["python"]
buildCommand = "pip install -r adreport/backend/requirements.txt"

[deploy]
startCommand = "cd adreport/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
